name: reviewai_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  google_mobile_ads: ^6.0.0
  google_generative_ai: ^0.4.7
  confetti: ^0.7.0
  device_info_plus: ^9.1.0 # 디바이스 정보 확인용
  package_info_plus: ^4.2.0 # 패키지 정보 확인용
  path_provider: ^2.1.1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/categories/
  fonts:
    - family: Do Hyeon
      fonts:
        - asset: assets/fonts/BMDOHYEON.otf

flutter_native_splash:
  color: "#FFFFFF"
  android: true
  ios: true
