name: eat_this_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  clarity_flutter: ^1.0.0

  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.2.0
  google_mobile_ads: ^5.1.0
  google_generative_ai: ^0.4.7
  confetti: ^0.7.0
  device_info_plus: ^9.1.0 # 디바이스 정보 확인용
  package_info_plus: ^4.2.0 # 패키지 정보 확인용
  path_provider: ^2.1.3
  fl_chart: ^0.68.0
  connectivity_plus: ^6.0.0

  timezone: ^0.9.2 # 이 패키지가 빠져있었습니다!
  geolocator: ^12.0.0
  geocoding: ^2.2.1
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/categories/
  fonts:
    - family: Do Hyeon
      fonts:
        - asset: assets/fonts/BMDOHYEON.otf

flutter_native_splash:
  color: "#FFFFFF"
  image: icon/app_icon.png # Use the app icon as the splash image
  android: true
  ios: true
