// Mocks generated by Mockito 5.4.6 from annotations
// in review_ai/test/data/repositories/recommendation_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:review_ai/data/datasources/recommendation_local_data_source.dart'
    as _i5;
import 'package:review_ai/data/datasources/recommendation_remote_data_source.dart'
    as _i2;
import 'package:review_ai/data/models/food_recommendation.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RecommendationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendationRemoteDataSource extends _i1.Mock
    implements _i2.RecommendationRemoteDataSource {
  @override
  _i3.Future<List<_i4.FoodRecommendation>> getFoodRecommendations({
    required String? category,
    required List<String>? recentFoods,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodRecommendations, [], {
              #category: category,
              #recentFoods: recentFoods,
            }),
            returnValue: _i3.Future<List<_i4.FoodRecommendation>>.value(
              <_i4.FoodRecommendation>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.FoodRecommendation>>.value(
                  <_i4.FoodRecommendation>[],
                ),
          )
          as _i3.Future<List<_i4.FoodRecommendation>>);
}

/// A class which mocks [RecommendationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecommendationLocalDataSource extends _i1.Mock
    implements _i5.RecommendationLocalDataSource {
  @override
  _i3.Future<List<_i4.FoodRecommendation>?> getCachedRecommendations(
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedRecommendations, [category]),
            returnValue: _i3.Future<List<_i4.FoodRecommendation>?>.value(),
            returnValueForMissingStub:
                _i3.Future<List<_i4.FoodRecommendation>?>.value(),
          )
          as _i3.Future<List<_i4.FoodRecommendation>?>);

  @override
  _i3.Future<void> cacheRecommendations(
    String? category,
    List<_i4.FoodRecommendation>? recommendations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheRecommendations, [
              category,
              recommendations,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [category]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
