// Mocks generated by Mockito 5.4.6 from annotations
// in review_ai/test/services/app_review_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:in_app_review/in_app_review.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:review_ai/services/remote_config_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [InAppReview].
///
/// See the documentation for Mockito's code generation for more information.
class MockInAppReview extends _i1.Mock implements _i2.InAppReview {
  MockInAppReview() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> requestReview() =>
      (super.noSuchMethod(
            Invocation.method(#requestReview, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> openStoreListing({
    String? appStoreId,
    String? microsoftStoreId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openStoreListing, [], {
              #appStoreId: appStoreId,
              #microsoftStoreId: microsoftStoreId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [RemoteConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfigService extends _i1.Mock
    implements _i4.RemoteConfigService {
  MockRemoteConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get reviewCooldownDays =>
      (super.noSuchMethod(
            Invocation.getter(#reviewCooldownDays),
            returnValue: 0,
          )
          as int);

  @override
  int get maxDailyAiReviews =>
      (super.noSuchMethod(Invocation.getter(#maxDailyAiReviews), returnValue: 0)
          as int);

  @override
  int get maxDailyRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#maxDailyRecommendations),
            returnValue: 0,
          )
          as int);

  @override
  int get reviewTargetRecommendationCount =>
      (super.noSuchMethod(
            Invocation.getter(#reviewTargetRecommendationCount),
            returnValue: 0,
          )
          as int);

  @override
  int get reviewTargetGenerationCount =>
      (super.noSuchMethod(
            Invocation.getter(#reviewTargetGenerationCount),
            returnValue: 0,
          )
          as int);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
