// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show debugPrint, defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:review_ai/services/config_service.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // 서버에서 가져온 API 키 (null이면 폴백 사용)
  static String? _serverAndroidApiKey;
  static String? _serverIosApiKey;

  /// 서버에서 Firebase API 키 로드 (앱 초기화 후 호출)
  static Future<void> loadServerKeys() async {
    try {
      _serverAndroidApiKey = await ConfigService.getFirebaseApiKey(
        platform: 'android',
      );
      _serverIosApiKey = await ConfigService.getFirebaseApiKey(platform: 'ios');
    } catch (e) {
      // 실패 시 폴백 기본값 사용
      debugPrint('Failed to load Firebase server keys: $e');
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    // SECURITY: API 키는 서버에서만 관리됩니다. 하드코딩 폴백 제거됨.
    apiKey: _serverAndroidApiKey ?? '',
    appId: '1:728734846473:android:b8758b19fdde6d70c872d8',
    messagingSenderId: '728734846473',
    projectId: 'reviewai-flutter',
    storageBucket: 'reviewai-flutter.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    // SECURITY: API 키는 서버에서만 관리됩니다. 하드코딩 폴백 제거됨.
    apiKey: _serverIosApiKey ?? '',
    appId: '1:728734846473:ios:5788de31bc676837c872d8',
    messagingSenderId: '728734846473',
    projectId: 'reviewai-flutter',
    storageBucket: 'reviewai-flutter.firebasestorage.app',
    iosBundleId: 'com.jonghyun.reviewapp',
  );
}
