// Mocks generated by Mockito 5.4.6 from annotations
// in review_ai/test/domain/usecases/generate_review_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:review_ai/domain/repositories/review_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewRepository extends _i1.Mock implements _i2.ReviewRepository {
  MockReviewRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<String>> generateReviews({
    required String? foodName,
    required double? deliveryRating,
    required double? tasteRating,
    required double? portionRating,
    required double? priceRating,
    required String? reviewStyle,
    _i4.File? foodImage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateReviews, [], {
              #foodName: foodName,
              #deliveryRating: deliveryRating,
              #tasteRating: tasteRating,
              #portionRating: portionRating,
              #priceRating: priceRating,
              #reviewStyle: reviewStyle,
              #foodImage: foodImage,
            }),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> validateImage(_i4.File? image) =>
      (super.noSuchMethod(
            Invocation.method(#validateImage, [image]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
